Pull request labels exposed in Pull Request generator template
infracloudio/argo-cd pull request #9
Opened 2022-11-21 07:48 UTC by maheshbaliga

Pull request labels have been exposed in Pull Request generator templates for Github, Gitea & Gitlab.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-11-21 12:02 UTC, theluckiesthuman requested changes

2022-11-21 12:42 UTC, mabhi approved these changes

2022-11-22 07:03 UTC, maheshbaliga commented on applicationset/services/pull_request/gitea.go
> +	labelNames := []string{}
Done.

2022-11-22 08:15 UTC, ApsTomar approved these changes

2022-11-22 10:45 UTC, theluckiesthuman approved these changes

2023-01-03 05:53 UTC, closed without merging